//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReport
    {
        public int Id { get; set; }
        public int ReportId { get; set; }
        public int CustomerId { get; set; }
        public string CubeName { get; set; }
        public string ServerName { get; set; }
        public string DBName { get; set; }
        public string DBType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Report Report { get; set; }
    }
}
