//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filter()
        {
            this.CustomerFilters = new HashSet<CustomerFilter>();
        }
    
        public int Id { get; set; }
        public string FilterName { get; set; }
        public string Type { get; set; }
        public string Field { get; set; }
        public string Value { get; set; }
        public string QueryStringKey { get; set; }
        public int ReportId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerFilter> CustomerFilters { get; set; }
        public virtual Report Report { get; set; }
    }
}
