//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomReports.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportsDbContext : DbContext
    {
        public ReportsDbContext()
            : base("name=ReportsDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bloc> Blocs { get; set; }
        public virtual DbSet<CustomerFilter> CustomerFilters { get; set; }
        public virtual DbSet<CustomerReport> CustomerReports { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Dimension> Dimensions { get; set; }
        public virtual DbSet<Filter> Filters { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Series_Measures> Series_Measures { get; set; }
    }
}
